In [5]:
import pandas as pd
from math import sqrt
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [8]:
import pandas as pd

movies_df = pd.read_csv("dataset.movie.csv")
ratings_df = pd.read_csv("dataset.ratings.csv")

print(movies_df.head())
print(ratings_df.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [9]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [10]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [11]:
#creating year column in movie dataframe and using extract function with regex on title column to copy the years with parentheses to year column
movies_df['year'] = movies_df.title.str.extract(r'(\(\d\d\d\d\))',expand=False)
#same method and function but we choose year column this time and choose the years without their parentheses
movies_df['year'] = movies_df.year.str.extract(r'(\d\d\d\d)',expand=False)
#using replace function in title to choose the years with parentheses and replace them with nothing, in order to delete them.
movies_df['title'] = movies_df['title'].str.replace(r'\(\d{4}\)', '', regex=True)
#using strip function to remove any extra space in beginning and end of movies titles
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [12]:
movies_df['genres'] = movies_df.genres.str.split('|')
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995

In [13]:
moviesWithGenres_df = movies_df.copy()

#for every index in every row (movie) iterrates 
for index, row in movies_df.iterrows():
    #for every index in genres array, make a column if not existed named that genre and write 1 for its value
    for genre in row['genres']:
        moviesWithGenres_df.at[index, genre] = 1
#naturally there are rows that doesnt have value (Nan) cause they didnt have that genre so, we fill them instead with 0 
moviesWithGenres_df = moviesWithGenres_df.fillna(0)
moviesWithGenres_df.head()

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men,"[Comedy, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
4,5,Father of the Bride Part II,[Comedy],1995,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [14]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [15]:
ratings_df = ratings_df.drop('timestamp', axis=1)
ratings_df.head()

   userId  movieId  rating
0       1      296     5.0
1       1      306     3.5
2       1      307     5.0
3       1      665     5.0
4       1      899     3.5

In [16]:
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
#making a dataframe from user input rating
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

In [17]:
#making a costume user input rating 
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
#making a dataframe from user input rating
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

In [18]:
#finding and choosing the movies that have same movie name as our input in movies dataframe and copying them to inputid variable
inputId = movies_df[movies_df['title'].isin(inputMovies['title'])]
#merging inputid(movies that the person saw) with his ratings, making the user rating matrix
inputMovies = pd.merge(inputId, inputMovies)
#deleting columns we dont need from our new dataframe
inputMovies = inputMovies.drop('genres', axis=1).drop('year', axis=1)
inputMovies

   movieId      title  rating
0        1  Toy Story     3.5
1        2    Jumanji     2.0

In [19]:
inputId.head()

   movieId      title                                             genres  year
0        1  Toy Story  [Adventure, Animation, Children, Comedy, Fantasy]  1995
1        2    Jumanji                     [Adventure, Children, Fantasy]  1995

In [20]:
userMovies = moviesWithGenres_df[moviesWithGenres_df['movieId'].isin(inputMovies['movieId'])]
userMovies

,movieId,title,genres,year,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [21]:
userMovies = userMovies.reset_index(drop=True)
#deleting columns we dont need to save memory by drop function and columns
userGenreTable = userMovies.drop('movieId', axis=1).drop('title', axis=1).drop('genres', axis=1).drop('year', axis=1)
userGenreTable

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller
0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
1,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [22]:
inputMovies['rating']

0    3.5
1    2.0
Name: rating, dtype: float64

In [23]:
userProfile = userGenreTable.transpose().dot(inputMovies['rating'])
userProfile

Adventure    5.5
Animation    3.5
Children     5.5
Comedy       3.5
Fantasy      5.5
Romance      0.0
Drama        0.0
Action       0.0
Crime        0.0
Thriller     0.0
dtype: float64

In [24]:
#creating genretable and choosing every movie in movies with genres dataframe but setting new index to them as their movieid
genreTable = moviesWithGenres_df.set_index(moviesWithGenres_df['movieId'])
#deleting the extra columns to save memory using drop function
genreTable = genreTable.drop('movieId', axis=1).drop('title', axis=1).drop('genres', axis=1).drop('year', axis=1)
genreTable.head()

,Adventure,Animation,Children,Comedy,Fantasy,Romance,Drama,Action,Crime,Thriller
movieId,,,,,,,,,,
1,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0
5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
genreTable.shape

(9, 10)

In [26]:
recommendationTable_df = ((genreTable*userProfile).sum(axis=1))/(userProfile.sum())
recommendationTable_df.head()

movieId
1    1.000000
2    0.702128
3    0.148936
4    0.148936
5    0.148936
dtype: float64

In [27]:
#sort decending with sort value function based on score
recommendationTable_df = recommendationTable_df.sort_values(ascending=False)
recommendationTable_df.head()

movieId
1    1.000000
2    0.702128
8    0.468085
3    0.148936
4    0.148936
dtype: float64

In [28]:
movies_df.loc[movies_df['movieId'].isin(recommendationTable_df.head(10).keys())]

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995
5,6,Heat,"[Action, Crime, Thriller]",1995
6,7,Sabrina,"[Comedy, Romance]",1995
7,8,Tom and Huck,"[Adventure, Children]",1995
8,9,Sudden Death,[Action],1995

In [29]:

#multiply each genre with its rating from user and summation them and divide them by the summation of userprofile
recommendationTable_df = ((genreTable*userProfile).sum(axis=1))/(userProfile.sum())
recommendationTable_df.head()

movieId
1    1.000000
2    0.702128
3    0.148936
4    0.148936
5    0.148936
dtype: float64

In [30]:
genreTable.shape

(9, 10)

In [31]:
movies_df.loc[movies_df['movieId'].isin(recommendationTable_df.head(10).keys())]

,movieId,title,genres,year
0,1,Toy Story,"[Adventure, Animation, Children, Comedy, Fantasy]",1995
1,2,Jumanji,"[Adventure, Children, Fantasy]",1995
2,3,Grumpier Old Men,"[Comedy, Romance]",1995
3,4,Waiting to Exhale,"[Comedy, Drama, Romance]",1995
4,5,Father of the Bride Part II,[Comedy],1995
5,6,Heat,"[Action, Crime, Thriller]",1995
6,7,Sabrina,"[Comedy, Romance]",1995
7,8,Tom and Huck,"[Adventure, Children]",1995
8,9,Sudden Death,[Action],1995

In [35]:
import pandas as pd

movies_df = pd.read_csv("dataset.movies1.csv")
ratings_df = pd.read_csv("dataset.ratings.csv")

print(movies_df.head())
print(ratings_df.head())

   movieId                               title  \
0        1                    Toy Story (1995)
1        2                      Jumanji (1995)
2        3             Grumpier Old Men (1995)
3        4            Waiting to Exhale (1995)
4        5  Father of the Bride Part II (1995)

                                        genres
0  Adventure|Animation|Children|Comedy|Fantasy
1                   Adventure|Children|Fantasy
2                               Comedy|Romance
3                         Comedy|Drama|Romance
4                                       Comedy
   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [36]:
#creating year column in movie dataframe and using extract function with regex in title to copy the years with parentheses to year column
movies_df['year'] = movies_df.title.str.extract(r'(\(\d\d\d\d\))',expand=False)
#same method and function but we choose year column this time and choose the years without their parentheses
movies_df['year'] = movies_df.year.str.extract(r'(\d\d\d\d)',expand=False)
#using replace function in title to choose the years with parentheses and replace them with nothing, in order to delete them.
movies_df['title'] = movies_df['title'].str.replace(r'\(\d{4}\)', '', regex=True)
#using strip function to remove any extra space in beginning and end of movies titles
movies_df['title'] = movies_df['title'].apply(lambda x: x.strip())
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [37]:
movies_df.head()

,movieId,title,genres,year
0,1,Toy Story,Adventure|Animation|Children|Comedy|Fantasy,1995
1,2,Jumanji,Adventure|Children|Fantasy,1995
2,3,Grumpier Old Men,Comedy|Romance,1995
3,4,Waiting to Exhale,Comedy|Drama|Romance,1995
4,5,Father of the Bride Part II,Comedy,1995

In [38]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [39]:
ratings_df.head()

   userId  movieId  rating   timestamp
0       1      296     5.0  1147880044
1       1      306     3.5  1147868817
2       1      307     5.0  1147868828
3       1      665     5.0  1147878820
4       1      899     3.5  1147868510

In [40]:
#user based recommendiation system
userInput = [
            {'title':'Breakfast Club, The', 'rating':5},
            {'title':'Toy Story', 'rating':3.5},
            {'title':'Jumanji', 'rating':2},
            {'title':"Pulp Fiction", 'rating':5},
            {'title':'Akira', 'rating':4.5}
         ] 
inputMovies = pd.DataFrame(userInput)
inputMovies

                 title  rating
0  Breakfast Club, The     5.0
1            Toy Story     3.5
2              Jumanji     2.0
3         Pulp Fiction     5.0
4                Akira     4.5

In [41]:
#finding and choosing the movies that have same movie name as our input in movies dataframe and copying them to inputid
inputId = movies_df[movies_df['title'].isin(inputMovies['title'].tolist())]
#merging inputid(movies that the person saw) with his ratings, making the user rating matrix
inputMovies = pd.merge(inputId, inputMovies)
#deleting columns we dont need from our new dataframe
inputMovies = inputMovies.drop('year', axis=1)
inputMovies

   movieId      title                                       genres  rating
0        1  Toy Story  Adventure|Animation|Children|Comedy|Fantasy     3.5
1        2    Jumanji                   Adventure|Children|Fantasy     2.0

In [43]:
# Filter users who watched the same movies as the input list
userSubset = ratings_df[
    ratings_df["movieId"].isin(inputMovies["movieId"].tolist())
]

# Show first 5 rows
userSubset.head()

Empty DataFrame
Columns: [userId, movieId, rating, timestamp]
Index: []

In [44]:
inputMovies = pd.DataFrame({
    "movieId": [1, 50]
})

In [45]:
userSubsetGroup = userSubset.groupby('userId')
userSubsetGroup

In [48]:
userSubsetGroup.get_group(name)

NameError: name 'name' is not defined

In [49]:
userSubsetGroup = userSubset.groupby("userId")

In [50]:
#sorting decending based on how many movies our raters have in common with person
userSubsetGroup = sorted(userSubsetGroup,  key=lambda x: len(x[1]), reverse=True)

In [53]:
userSubsetGroup = userSubset.groupby("userId")

In [56]:
# Group the dataframe
userSubsetGroup = userSubset.groupby("userId")

# Convert groupby object to list
userSubsetGroup_list = list(userSubsetGroup)

# Check types
print(type(userSubsetGroup_list))      # list
print(type(userSubsetGroup_list[0]))   # tuple
print(type(userSubsetGroup_list[0][1]))  # pandas DataFrame

<class 'list'>

IndexError: list index out of range

In [61]:
#Store the Pearson Correlation in a dictionary, where the key is the user Id and the value is the coefficient
pearsonCorrelationDict = {}

#For every user in every group in our subset
for name, group in userSubsetGroup:
    #sort by movieid
    group = group.sort_values(by='movieId')
    inputMovies = inputMovies.sort_values(by='movieId')
    #Get the N for the formula, caculating how many common movies they have
    nRatings = len(group)
    #Get the review scores for the movies that they both have in common
    temp_df = inputMovies[inputMovies['movieId'].isin(group['movieId'].tolist())]
    #And then store them in a temporary buffer variable in a list format to facilitate future calculations
    tempRatingList = temp_df['rating'].tolist()
        # current user group reviews in a list format
    tempGroupList = group['rating'].tolist()
    #pearson correlation formula
    Sxx = sum([i**2 for i in tempRatingList]) - pow(sum(tempRatingList),2)/float(nRatings)
    Syy = sum([i**2 for i in tempGroupList]) - pow(sum(tempGroupList),2)/float(nRatings)
    Sxy = sum( i*j for i, j in zip(tempRatingList, tempGroupList)) - sum(tempRatingList)*sum(tempGroupList)/float(nRatings)
    
    #checking not to have 0 in base and devide to complete the formula
    if Sxx != 0 and Syy != 0:
        pearsonCorrelationDict[name] = Sxy/sqrt(Sxx*Syy)
    else:
        pearsonCorrelationDict[name] = 0

In [62]:
pearsonCorrelationDict

{}

In [66]:
pearsonDF["userId"] = pearsonDF.index

In [67]:
pearsonDF.index = range(len(pearsonDF))

In [76]:
import pandas as pd

# Load dataset
ratings_df = pd.read_csv("dataset.ratings.csv")

# Example: pearson similarity dictionary
pearsonCorrelationDict = {1:0.9, 2:0.8, 3:0.7, 4:0.6, 5:0.5}

# Convert dictionary to DataFrame
pearsonDF = pd.DataFrame.from_dict(pearsonCorrelationDict, orient="index")
pearsonDF.columns = ["similarityIndex"]

# Add userId column
pearsonDF["userId"] = pearsonDF.index

# Reset index
pearsonDF.reset_index(drop=True, inplace=True)

# Get top 50 similar users
topUsers = pearsonDF.sort_values(by="similarityIndex", ascending=False).head(50)

# Merge with ratings dataset
topUsersRating = pd.merge(topUsers, ratings_df, on="userId", how="inner")

# Show result
topUsersRating.head()

   similarityIndex  userId  movieId  rating   timestamp
0              0.9       1      296     5.0  1147880044
1              0.9       1      306     3.5  1147868817
2              0.9       1      307     5.0  1147868828
3              0.9       1      665     5.0  1147878820
4              0.9       1      899     3.5  1147868510

In [77]:
tempTopUsersRating = topUsersRating.groupby('movieId').sum()[['similarityIndex','weightedRating']]
tempTopUsersRating.columns = ['sum_similarityIndex','sum_weightedRating']
tempTopUsersRating.head()

KeyError: "['weightedRating'] not in index"

In [78]:
# Create weighted rating
topUsersRating["weightedRating"] = topUsersRating["similarityIndex"] * topUsersRating["rating"]

# Group by movieId and calculate sum
tempTopUsersRating = topUsersRating.groupby("movieId").sum()[["similarityIndex", "weightedRating"]]

# Rename columns
tempTopUsersRating.columns = ["sum_similarityIndex", "sum_weightedRating"]

# Show result
tempTopUsersRating.head()

         sum_similarityIndex  sum_weightedRating
movieId
296                      0.9                4.50
306                      0.9                3.15
307                      0.9                4.50
665                      0.9                4.50
899                      0.9                3.15

In [80]:
#Creates an empty dataframe
recommendation_df = pd.DataFrame()
#Now we take the weighted average
recommendation_df['weighted average recommendation score'] = tempTopUsersRating['sum_weightedRating']/tempTopUsersRating['sum_similarityIndex']
recommendation_df['movieId'] = tempTopUsersRating.index
recommendation_df.head()

         weighted average recommendation score  movieId
movieId
296                                        5.0      296
306                                        3.5      306
307                                        5.0      307
665                                        5.0      665
899                                        3.5      899

In [81]:
recommendation_df = recommendation_df.sort_values(by='weighted average recommendation score', ascending=False)
recommendation_df.head(10)

         weighted average recommendation score  movieId
movieId
296                                        5.0      296
307                                        5.0      307
665                                        5.0      665
1237                                       5.0     1237
1088                                       4.0     1088
1250                                       4.0     1250
306                                        3.5      306
899                                        3.5      899
1175                                       3.5     1175
1217                                       3.5     1217